### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**

### CODE REVIEW

**Review by alexAubin — APPROVED** [review]

**Comment by ericgaspar** [comment]
@fflorent  the app works know in testing branch with `--production` option. I'm just facing a weird bug 😱

Capture d’écran 2022-02-05 à 19 12 45

**Comment by fflorent** [comment]
> @fflorent the app works know in testing branch with `--production` option. I'm just facing a weird bug scream
> 
> Capture d’écran 2022-02-05 à 19 12 45

I think it should be better if you update the commit to 00b8c682a2ef45e5f2399588a355d845c0d0016b. That should work again

**Comment by ericgaspar** [comment]
!testme

**Comment by yalh76** [comment]
@ericgaspar , do we merge ?

**Comment by ericgaspar** [comment]
It is not working... le souci could be upstream

**Comment by ericgaspar** [comment]
!testme

**Comment by fflorent** [comment]
> It is not working... le souci could be upstream

In order to work, I think you need to generate words in a file.

You may ask the author some instructions on how to generate this list of words.

Florent

**Comment by ericgaspar** [comment]
I have tested Yalh76 #8 branch and it work as expected... So I guess it wasn't upstream.
Can you test the testing branch to confirm?

**Comment by fflorent** [comment]
It works.

Does the word remain the same or does it change everyday?

Florent

**Comment by ericgaspar** [comment]
let's wait till tomorrow and see

**Comment by yalh76** [comment]
!testme

**Pull request merged**
